name: cupertino_ui
description: The official Flutter Cupertino Design Library, implementing the iOS design system.
version: 0.0.2
publish_to: none
repository: https://github.com/flutter/packages/tree/main/packages/cupertino_ui
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A%20cupertino%22

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

workspace:
  - example

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter

dev_dependencies:
  clock: ^1.1.2
  flutter_goldens:
    path: ../../script/flutter_goldens
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  # To track memory leaks.
  leak_tracker_flutter_testing: ^3.0.10
  material_ui:
    # TODO(justinmc): Use the pub.dev package when published.
    path: ../material_ui

topics:
  - ui
  - widgets
  - cupertino
  - ios
