# A list of packages and their minimum required code coverage.
# Only packages listed in this file will be checked for code coverage.
# If a package drops below its listed threshold, the CI check will fail.
custom_coverage_minimums:
  camera_android: 30.0
  camera_android_camerax: 18.3
