// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon, do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: depend_on_referenced_packages

import 'dart:io';
import 'package:jnigen/jnigen.dart';
import 'package:logging/logging.dart';

void main() async {
  Directory.current = Platform.script.resolve('../..').toFilePath();
  await generateJniBindings(
    Config(
      preamble: '''
      // Copyright 2013 The Flutter Authors\n// Use of this source code is governed by a BSD-style license that can be\n// found in the LICENSE file.
      ''',
      androidSdkConfig: AndroidSdkConfig(addGradleDeps: true, androidExample: '.'),
      summarizerOptions: SummarizerOptions(backend: SummarizerBackend.asm),
      outputConfig: OutputConfig(
        dartConfig: DartCodeOutputConfig(
          path: Uri.file('lib/src/native_interop_example.g.jni.dart'),
          structure: OutputStructure.singleFile,
        ),
      ),
      logLevel: Level.ALL,
      classPath: [Uri.directory('build/app/tmp/kotlin-classes/release')],

      classes: [
        'dev.flutter.pigeonnativeinteropapp.FlutterError',
        'dev.flutter.pigeonnativeinteropapp.NativeInteropExampleApi',
        'dev.flutter.pigeonnativeinteropapp.NativeInteropExampleApiRegistrar',
      ],
    ),
  );
}
