name: gen_defaults
description: A command line script to generate Material component defaults from the token database.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  args: ^2.7.0
  flutter:
    sdk: flutter
  meta: ^1.18.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.31.1
