include: ../../analysis_options.yaml

analyzer:
  exclude:
    - "test_fixes/**"
    # TODO(justinmc): Remove the following exclusions when cross-imports are
    # fixed. See https://github.com/flutter/flutter/issues/177028.
    - "test/adaptive_text_selection_toolbar_test.dart"
    - "test/animated_icons_test.dart"
    - "test/app_bar_sliver_test.dart"
    - "test/app_bar_test.dart"
    - "test/autocomplete_test.dart"
    - "test/bottom_navigation_bar_test.dart"
    - "test/bottom_sheet_test.dart"
    - "test/calendar_date_picker_test.dart"
    - "test/card_test.dart"
    - "test/checkbox_list_tile_test.dart"
    - "test/checkbox_test.dart"
    - "test/chip_test.dart"
    - "test/circle_avatar_test.dart"
    - "test/color_scheme_test.dart"
    - "test/data_table_test.dart"
    - "test/date_picker_test.dart"
    - "test/date_range_picker_test.dart"
    - "test/dialog_test.dart"
    - "test/drawer_test.dart"
    - "test/dropdown_menu_test.dart"
    - "test/dropdown_test.dart"
    - "test/elevated_button_test.dart"
    - "test/filled_button_test.dart"
    - "test/filter_chip_test.dart"
    - "test/flexible_space_bar_test.dart"
    - "test/floating_action_button_test.dart"
    - "test/icon_button_test.dart"
    - "test/ink_well_test.dart"
    - "test/input_date_picker_form_field_test.dart"
    - "test/list_tile_test.dart"
    - "test/material_button_test.dart"
    - "test/material_test.dart"
    - "test/menu_anchor_test.dart"
    - "test/navigation_rail_test.dart"
    - "test/outlined_button_test.dart"
    - "test/popup_menu_test.dart"
    - "test/radio_list_tile_test.dart"
    - "test/radio_test.dart"
    - "test/range_slider_test.dart"
    - "test/scaffold_test.dart"
    - "test/search_anchor_test.dart"
    - "test/search_test.dart"
    - "test/selectable_text_test.dart"
    - "test/slider_test.dart"
    - "test/sliver_app_bar_test.dart"
    - "test/switch_list_tile_test.dart"
    - "test/switch_test.dart"
    - "test/tabs_test.dart"
    - "test/text_button_test.dart"
    - "test/text_field_test.dart"
    - "test/text_form_field_test.dart"
    - "test/text_selection_test.dart"
    - "test/time_picker_test.dart"
    - "test/toggle_buttons_test.dart"
    - "test/tooltip_theme_test.dart"

formatter:
  page_width: 100
