name: test_plugin
description: Pigeon test harness for primary plugin languages.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.test_plugin
        pluginClass: TestPlugin
      ios:
        pluginClass: TestPlugin
        sharedDarwinSource: true
      linux:
        pluginClass: TestPlugin
      macos:
        pluginClass: TestPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: TestPluginCApi

dependencies:
  ffi: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/ffi
      ref: 27890daeab690209603a979c7fbb54b22a3c878f
  flutter:
    sdk: flutter
  jni: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/jni
      ref: 27890daeab690209603a979c7fbb54b22a3c878f

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  ffi: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/ffi
      ref: 27890daeab690209603a979c7fbb54b22a3c878f
  ffigen: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/ffigen
      ref: 27890daeab690209603a979c7fbb54b22a3c878f
  objective_c: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/objective_c
      ref: 27890daeab690209603a979c7fbb54b22a3c878f
  swift2objc: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/swift2objc
      ref: 27890daeab690209603a979c7fbb54b22a3c878f