name: githooks
description: Git hooks for the flutter/packages repository. For more information and instructions to install the hooks, see README.md
publish_to: none

environment:
  sdk: ^3.10.0-0

dependencies:
  args: any
  path: any

dev_dependencies:
  test: any
