name: cross_file_darwin
description: Implementation of cross_file_platform_interface for iOS and macOS.
repository: https://github.com/flutter/packages/tree/main/packages/cross_file/cross_file_darwin
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+cross_file%22
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

flutter:
  plugin:
    implements: cross_file
    platforms:
      ios:
        dartPluginClass: CrossFileDarwin
        pluginClass: CrossFileDarwinPlugin
        sharedDarwinSource: true
      macos:
        dartPluginClass: CrossFileDarwin
        pluginClass: CrossFileDarwinPlugin
        sharedDarwinSource: true

dependencies:
  cross_file_io:
    git:
      url: https://github.com/bparrishMines/packages
      ref: new_crossfile
      path: packages/cross_file/cross_file_io
  cross_file_platform_interface:
    git:
      url: https://github.com/bparrishMines/packages
      ref: new_crossfile
      path: packages/cross_file/cross_file_platform_interface
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  objective_c: ^9.4.1
  path: ^1.9.1

dev_dependencies:
  ffigen: ^20.1.1
  flutter_test:
    sdk: flutter

topics:
  - file
  - cross-file
