name: alternate_language_test_plugin_example
description: Pigeon test harness for alternate plugin languages.
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  alternate_language_test_plugin:
    path: ../
  flutter:
    sdk: flutter
  shared_test_plugin_code:
    path: ../../shared_test_plugin_code

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  ffi: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/ffi
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323
  ffigen: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/ffigen
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323
  objective_c: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/objective_c
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323
  swift2objc: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/swift2objc
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323

flutter:
  uses-material-design: true
