name: alternate_language_test_plugin
description: Pigeon test harness for alternate plugin languages.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.alternate_language_test_plugin
        pluginClass: AlternateLanguageTestPlugin
      ios:
        pluginClass: AlternateLanguageTestPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: AlternateLanguageTestPlugin
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  ffi:
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/ffi
      ref: a1b844b93b95882fc9d47a19371a63a163132dd6
  ffigen:
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/ffigen
      ref: a1b844b93b95882fc9d47a19371a63a163132dd6
  objective_c:
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/objective_c
      ref: a1b844b93b95882fc9d47a19371a63a163132dd6
  swift2objc:
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/swift2objc
      ref: a1b844b93b95882fc9d47a19371a63a163132dd6
