// Autogenerated from Pigeon, do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: depend_on_referenced_packages

import 'dart:io';
import 'package:jnigen/jnigen.dart';
import 'package:logging/logging.dart';

void main() async {
  Directory.current = Platform.script.resolve('.').toFilePath();
  await generateJniBindings(
    Config(
      androidSdkConfig: AndroidSdkConfig(addGradleDeps: true, androidExample: './'),
      summarizerOptions: SummarizerOptions(backend: SummarizerBackend.asm),
      outputConfig: OutputConfig(
        dartConfig: DartCodeOutputConfig(
          // Path is relative to appDirectory.
          path: Uri.file('../../shared_test_plugin_code/lib/src/generated/ni_tests.gen.jni.dart'),
          structure: OutputStructure.singleFile,
        ),
      ),
      logLevel: Level.ALL,
      classPath: [Uri.directory('build/app/tmp/kotlin-classes/release')],

      classes: [
        'com.example.test_plugin.NiTestsError',
        'com.example.test_plugin.NIHostIntegrationCoreApi',
        'com.example.test_plugin.NIHostIntegrationCoreApiRegistrar',
        'com.example.test_plugin.NIFlutterIntegrationCoreApi',
        'com.example.test_plugin.NIFlutterIntegrationCoreApiRegistrar',
        'com.example.test_plugin.NIUnusedClass',
        'com.example.test_plugin.NIAllTypes',
        'com.example.test_plugin.NIAllNullableTypes',
        'com.example.test_plugin.NIAllNullableTypesWithoutRecursion',
        'com.example.test_plugin.NIAllClassesWrapper',
        'com.example.test_plugin.NIAnEnum',
        'com.example.test_plugin.NIAnotherEnum',
      ],
    ),
  );
}
