name: test_plugin_example
description: Pigeon test harness for primary plugin languages.
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  ffi: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/ffi
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323
  ffigen: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/ffigen
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323
  flutter:
    sdk: flutter
  jni: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/jni
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323
  jnigen: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/jnigen
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323
  pub_semver: ^2.2.0
  shared_test_plugin_code:
    path: ../../shared_test_plugin_code
  swiftgen: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/swiftgen
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323
  test_plugin:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  logging: ^1.3.0
  pigeon:
    path: ../../..
  swift2objc: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/swift2objc
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323

flutter:
  uses-material-design: true

dependency_overrides:
  ffi: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/ffi
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323
  ffigen: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/ffigen
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323
  objective_c: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/objective_c
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323
  swift2objc: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/swift2objc
      ref: d3cda4fc851a3e1dff07558f5616d1eb4502e323