name: file_selector_windows
description: Windows implementation of the file_selector plugin.
repository: https://github.com/flutter/packages/tree/main/packages/file_selector/file_selector_windows
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+file_selector%22
version: 0.10.0

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

flutter:
  plugin:
    implements: file_selector
    platforms:
      windows:
        dartPluginClass: FileSelectorWindows
        pluginClass: FileSelectorWindows

dependencies:
  file_selector_platform_interface: ^3.0.0
  flutter:
    sdk: flutter
  meta: ^1.10.0

dev_dependencies:
  cross_file_platform_interface: ^1.0.0
  flutter_test:
    sdk: flutter
  pigeon: ^27.3.2

topics:
  - files
  - file-selection
  - file-selector
# FOR TESTING AND INITIAL REVIEW ONLY. DO NOT MERGE.
# See https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changing-federated-plugins
dependency_overrides:
  file_selector_platform_interface: {path: ../../../packages/file_selector/file_selector_platform_interface}
